### ISSUE TITLE
About the error during the Linux

### ISSUE THREAD

**Issue by MingshanHe** [martisak/dotnets#4]
I have run the code at this environment.
OS: Ubuntu 20.04
Python: 3.8.5

I have already installed the Graphviz but I have following error. Please help me. Thanks.

Error:
python3 dotnets.py | dot -Tpng 
�PNG

bKGD������� IDATx���{\L��8�s�RӽTRJ.%&��B!J.��X�n)�m�&bWȊH%��\Ҋ"�(�HwE.Q*��ej.�?��;����̙3�������9��Ω��y�_�����"!�vx�PP8 @@�PP8 @@�PP8 @@�PP8 @@�PP8 @$SQQ�f�Eu��Eэ�9�-���-�6A�ׯ�y��`@����y�̙3�ܹSDk#F�5j��+�9����<p��oA$0x�ô

                                             �� +���-�
Row�K�ΝâSS�۽��o��à_FP��0��1�����n1à�H����a8""��
��>v����㵴��O��������s�cN�<9q�DMMMkk���ô&��è������léééuuu

                                                         �S�N��'�n�â����+à�H�����VRRڼy�#V�XQTT$�1l6���eǎVVV����

����>����������Y�vmkk�M�nݺ%���;n1��z'7P$H��0���)))�9s�����֬Y�d2�Wjjj
                                                                   ��ۏ�'N�0ù��-�+���AO�<�çt���%%%Ȼ/_�� ���ê&��"p��y���$
                                                                                                                       �������3�+,+((H�)gϞ�P(�������

**Comment by martisak** [comment]
You need to redirect the output, either to a file or to a viewer.
For example 
```
python3 dotnets.py | dot -Tpng > output.png
```

**Comment by MingshanHe** [comment]
Yeah, it works. Thank you.
